INSERT INTO ENDERECO (NUMERO, CEP, BAIRRO, CIDADE, ESTADO, COMPLEMENTO, LOGRADOURO) VALUES ('123', '12345-678', 'Centro', 'São Paulo', 'SP', 'Próximo ao mercado', 'Rua A');
INSERT INTO ENDERECO (NUMERO, CEP, BAIRRO, CIDADE, ESTADO, COMPLEMENTO, LOGRADOURO) VALUES ('456', '98765-432', 'Jardim', 'Rio de Janeiro', 'RJ', NULL, 'Av. Brasil');

INSERT INTO FILIAL (FK_ENDERECO, NOME) VALUES (1, 'Filial São Paulo');
INSERT INTO FILIAL (FK_ENDERECO, NOME) VALUES (2, 'Filial Rio');

INSERT INTO FUNCIONARIO (FK_FILIAL, NOME) VALUES (1, 'João Silva');
INSERT INTO FUNCIONARIO (FK_FILIAL, NOME) VALUES (1, 'Maria Oliveira');
INSERT INTO FUNCIONARIO (FK_FILIAL, NOME) VALUES (2, 'Carlos Souza');

INSERT INTO MOTO (ANO, FK_FILIAL, PLACA, MODELO, TIPO_COMBUSTIVEL) VALUES (2022, 1, 'ABC1D23', 'MOTTU_E', 'Gasolina');
INSERT INTO MOTO (ANO, FK_FILIAL, PLACA, MODELO, TIPO_COMBUSTIVEL) VALUES (2023, 1, 'XYZ9H87', 'MOTTU_SPORT', 'Gasolina');
INSERT INTO MOTO (ANO, FK_FILIAL, PLACA, MODELO, TIPO_COMBUSTIVEL) VALUES (2021, 2, 'JKL3W45', 'MOTTU_POP', 'Eletrico');

INSERT INTO LOCALIZACAO (PONTOX, PONTOY, DATA_HORA, FK_MOTO, FONTE) VALUES (-46.6, 2.2, '2025-05-10 08:30:00', 1, 'GPS');
INSERT INTO LOCALIZACAO (PONTOX, PONTOY, DATA_HORA, FK_MOTO, FONTE) VALUES (-20.1, 13.4, '2025-05-10 08:35:00', 1, 'GPS');
INSERT INTO LOCALIZACAO (PONTOX, PONTOY, DATA_HORA, FK_MOTO, FONTE) VALUES (-43.2, 22.8, '2025-05-10 09:00:00', 3, 'Visao_Computacional');
INSERT INTO LOCALIZACAO (PONTOX, PONTOY, DATA_HORA, FK_MOTO, FONTE) VALUES (47.9, -23.1, '2025-05-10 08:40:00', 2, 'Sensor');
